image: openjdk:8-jdk

test:
  stage: test
  services:
    - openjdk:8
  artifacts:
    name: "TestRunnerLogs"
    when: always
    paths:
      - takipi/log/
  script:
    - curl -v -s https://s3.amazonaws.com/app-takipi-com/deploy/linux/takipi-agent-latest.tar.gz --output takipi-agent.tar.gz
    - tar xvzf takipi-agent.tar.gz
    - rm takipi-agent.tar.gz

    - echo takipi.deployment.name=job-${CI_COMMIT_SHORT_SHA} > takipi/agent.properties
    - echo takipi.application.name=${CI_PROJECT_NAME} >> takipi/agent.properties
    - echo takipi.collector.host=${TAKIPI_COLLECTOR_HOST} >> takipi/agent.properties
    - echo takipi.collector.port=${TAKIPI_COLLECTOR_PORT} >> takipi/agent.properties
    - echo shutdownGraceTime=20000 >> takipi/agent.properties
  
    - ./mvnw -DargLine=-agentpath:./takipi/lib/libTakipiAgent.so test

overops:
  stage: test
  when: on_success
  allow_failure: false
  artifacts:
    name: "OverOps-Quality-Report-Job-$CI_JOB_ID"
    when: always
    paths:
      - overops-quality-report/
    untracked: true
    expire_in: 90 days
  script:
    - mkdir overops-quality-report
    - chmod +x quality-report.sh
    - ./quality-report.sh