image: ccaspanello/overops-gitlab-plugin:latest

variables:
  OVEROPS_APPLICATION_NAME: ${CI_PROJECT_NAME}
  OVEROPS_DEPLOYMENT_NAME: job-${CI_COMMIT_SHORT_SHA}
  OVEROPS_MARK_UNSTABLE: "true"
  OVEROPS_NEW_EVENTS: "true"
  OVEROPS_RESURFACED_ERRORS: "true"
  OVEROPS_MAX_ERROR_VOLUME: 5
  OVEROPS_MAX_UNIQUE_ERRORS: 5
  OVEROPS_CRITICAL_EXCEPTION_TYPES: "ExampleUncaughtException, SAXParseException"
  # OVEROPS_REGEX_FILTER:
  OVEROPS_PRINT_TOP_ISSUES: 5
  OVEROPS_ACTIVE_TIMESPAN: "0m"
  OVEROPS_BASE_LINE_TIMESPAN: "1d"
  OVEROPS_MIN_VOLUME_THRESHOLD: 1
  OVEROPS_MIN_ERROR_RATE_THRESHOLD: "0.0001"
  OVEROPS_APPLY_SEASONALITY: "true"
  OVEROPS_SHOW_EVENTS_FOR_PASSED_GATES: "true"
  OVEROPS_DEBUG: "true"

test:
  stage: test
  services:
    - openjdk:8
  artifacts:
    name: "TestRunnerLogs"
    when: always
    paths:
      - takipi/log/
  script:
    - tar xvzf takipi-agent-4.50.0.tar.gz
    - echo takipi.collector.host=${TAKIPI_COLLECTOR_HOST} >> takipi/agent.properties
    - echo takipi.collector.port=${TAKIPI_COLLECTOR_PORT} >> takipi/agent.properties
    - echo takipi.application.name=${CI_PROJECT_NAME} >> takipi/agent.properties
    - echo takipi.deployment.name=job-${CI_COMMIT_SHORT_SHA} >> takipi/agent.properties
    - echo shutdownGraceTime=20000 >> takipi/agent.properties
    - ./mvnw -DargLine=-agentpath:./takipi/lib/libTakipiAgent.so test
overops:
  stage: test
  when: on_success
  allow_failure: false
  artifacts:
    name: "OverOps Quality Report $CI_JOB_ID"
    when: always
    paths:
      - quality-report.html
    untracked: true
    expire_in: 90 days
  script:
    - /opt/run-quality-report.sh
